allowBuilds:
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@3.0.184"
  - "@ai-sdk/provider-utils@4.0.49"
  - "@ai-sdk/react@3.0.273"
  - ai@6.0.270
  - "@cloudflare/vite-plugin@1.60.0"
  - "@cloudflare/workers-types@5.20260924.1"
  - "@cloudflare/sandbox@0.12.10"
  - miniflare@5.20260923.0-alpha
  - wrangler@4.139.0
