// Generated by EmDash after the agent creates the site's schema.
// Do not edit manually.

/// <reference types="emdash/locals" />

import "emdash";

declare module "emdash" {
	interface EmDashCollections {}
}
